### ISSUE TITLE
sidebar coloring in themes is likely broken

### ISSUE THREAD

**Issue by sergiorussia** [tinted-theming/tinted-sublime-text#2]
hi. first of all thanks for great work of supporting sublime text, accidentally discovered tinted themes after base16 :)

i was trying to use (dark) theme with sublime and found out that most of them (all?) are broken in side bar tabs coloring

tried themes:
- tomorrow night eighties
- gruvbox material dark medium
- everforest
- nord
- ...

check this out. adaptive theme looks just fine:
![Screenshot from 2024-08-12 23-27-14](https://github.com/user-attachments/assets/e327e647-4890-46d4-9b8c-baff8c55cd23)

tinted theme looks awful **in side bar**:
![Screenshot from 2024-08-12 23-27-49](https://github.com/user-attachments/assets/b29b8c41-cea1-48d3-84d3-66adf72d7859)
- looks like selected/highlighted row color and inactive color should be swapped/tuned/fixed
- `OPEN FILES` title is not visible at all
- extra empty row after last opened file (line after `file 5`, i think it's not theme issue per se, but definitely a coloring issue)

i'm using latest sublime text build 4180

my prefs are very basic, nothing special
```json
{
	"close_windows_when_empty": true,
	"color_scheme": "Packages/tinted_theming/color-schemes/base16-tomorrow-night-eighties.sublime-color-scheme",
	"ensure_newline_at_eof_on_save": true,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage",
	],
	"tab_size": 2,
	"theme": "Adaptive.sublime-theme",
	"translate_tabs_to_spaces": true,
	"dark_theme": "Default Dark.sublime-theme",
	"light_theme": "Default.sublime-theme",
	"index_files": true,
}
```

ps: light themes are broken too in that regard

**Comment by JamyGolden** [comment]
Hi 😊 Thanks for creating the ticket. I’ll have a look at it this week and get back to you.

**Comment by JamyGolden** [comment]
What OS and sublime text version are you using?

**Comment by JamyGolden** [comment]
nvm I thought adaptive theme image was with tinted-sublime-text, yeah I get the same will fix.

**Comment by sergiorussia** [comment]
i'm on latest fedora and lts ubuntu. 
both images are with tinted ui color scheme, diff is in ui theme.

ps: and btw adaptive theme is really just fine with many color schemes out there, maybe it's not worth maintaining theme at all :) anyway thanks for your effort

**Comment by JamyGolden** [comment]
Thanks for reporting. I don't use sublime much (mostly to edit large files :smile:) I managed to fix it quite easily. Hopefully it fixes it at least! https://github.com/tinted-theming/tinted-sublime-text/pull/3

**Comment by JamyGolden** [comment]
Just merged the PR so this should issue should be fixed now
