### ISSUE TITLE
coloring in dark themes is partially broken

### ISSUE THREAD

**Issue by sergiorussia** [tinted-theming/tinted-sublime-text#4]
continuation of #2

another few places seems need fixing. looks like the same issue.
here are some screenshots with theme `Tomorrow Night Eighties` selected via `Tinted Theming: Activate Theme`

command palette - unreadable selected item
![Screenshot from 2024-08-24 19-51-16](https://github.com/user-attachments/assets/f32446c1-063a-4271-ade9-1c31c8df6f6c)

quick switch project - ditto
![Screenshot from 2024-08-24 19-53-28](https://github.com/user-attachments/assets/5b37126c-bcbe-48fe-b963-8569efa7afa8)

(various) input fields, eg try Find & Replace or View > Show Console - wrong border comparing to fields themselves
![Screenshot from 2024-08-24 19-56-59](https://github.com/user-attachments/assets/eef14fe6-4b76-4f67-84a6-60e101514b02)

**Comment by sergiorussia** [comment]
@JamyGolden could you take a look?

ps: just thoughts: maybe it's not worth supporting ui **theme** at all? many-many themes looks just fine with Adaptive and some well-known themes even relies on it (eg see [Catppuccin](https://github.com/catppuccin/sublime-text?tab=readme-ov-file#activation)) or does not bother at all (eg see [Nord](https://packagecontrol.io/packages/Nord) or [Dracula](https://draculatheme.com/sublime))

**Comment by JamyGolden** [comment]
I've created a fix for this and merged it: https://github.com/tinted-theming/tinted-sublime-text/pull/5

Can you check to see if it looks good for you?

**Comment by sergiorussia** [comment]
@JamyGolden mostly yes, except Quick Switch Project panel is broken now, either transparent or broken render, check this out
![image](https://github.com/user-attachments/assets/56db9b8e-467b-482a-b29e-8e0cd7eaf92f)
![image](https://github.com/user-attachments/assets/842976de-75c5-4ba2-9aff-663f6260ca3c)
checked it with Adaptive theme - works fine

you've said you couldn't find quick switch panel - it's under the Project menu > Quick Switch Project (Ctrl+Alt+P)

and too low contrast in Find'n'Replace's Where field hint - but i dunno, maybe it's just specific themes' issue

**Comment by JamyGolden** [comment]
Thanks! I've fixed it, it should look not-broken now :sweat_smile: https://github.com/tinted-theming/tinted-sublime-text/pull/6

Yeah I agree the text contrast isn't great. I need to figure out where exactly this is set. It doesn't seem to be in the `*.sublime-theme` file like everything else has been. I'll be looking at it this coming week.

**Comment by JamyGolden** [comment]
I've just merged a fix which increases contrast between font and input background in text fields: https://github.com/tinted-theming/tinted-sublime-text/pull/7

**Comment by sergiorussia** [comment]
@JamyGolden now it looks like it should, nice! also noticed you've fixed base fg color from `base04` to `base05` - just like it should be, finally. thanks! i think we could close the issue then
